#! python

def build(ctx):
    ctx(features='run_py_script',
        source='plot_sim_results.py',
        target=[
            ctx.path_to(ctx, 'OUT_FIGURES', 'UdistanceNaiveL3.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'UdistanceP4.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'CCPAdoption_counter_diff.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'CCPAdoption.pdf')
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS','fig1Data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS','CCPCounterdiffData.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'L3naive_data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'P4_data.mat')         
        ],
        name='plot_heatmaps'
        )

    ctx(features='run_py_script',
        source='format_est_results.py',
        target=[
            ctx.path_to(ctx, 'OUT_TABLES', 'estMD_sophi_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMD_naive_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estOLS_L3_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_norm_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_normTerm_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_naive_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMD_rn_sophi_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_rn_new.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'estMLE_rn_eD_new.tex')
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'md_table_data.csv'), 
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'md_table_data_naive.csv'), 
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'md_rn_table_data.csv'),         
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_norm_table_data.csv'),         
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_normTerm_table_data.csv'),         
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_table_data.csv'),   
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_rn_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_rn_eD_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_naive_table_data.csv'),             
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'ols_table_data.csv')         
        ],
        name='format_sim_results_tables'
    )