#! python

from typing import Text
import uuid


def build(ctx):

    ctx(features='run_m_script',
        source='OneTerminatingAction/DDCOneTerminate.m',
        # SW: I only add a few targets here, please check that at some point they are comprehensive.
        target=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'postestimation_DDC_oneTA.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'md_table_data_naive.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'L3_data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'L3naive_data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'P4_data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'fig1Data.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'CCPCounterNormTermData.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'CCPCounterData.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'CCPCounterNormTermBandData.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'CCPCounterBandData.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'ols_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_norm_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_normTerm_table_data.csv'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'mle_naive_table_data.csv'),
            ctx.path_to(ctx, 'OUT_TABLES', 'bdEst.mat'),
            ctx.path_to(ctx, 'OUT_TABLES', 'singularityAs5.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'singularityQ.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'Uverify.tex')
        ],
        deps=[
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/backInduction.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/bellman.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/CCP_generator.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/criterianNoinv.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/EstMD_LastPeriods.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/flowpayoffs.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/logitfit.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/MLEstimation.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/myconstraint.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/nLogLik.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/randomdiscrete.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/simulateData_CCP.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/solutionplot.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/verification_naive.m'),
            ctx.path_to(ctx, 'IN_ANALYSIS','OneTerminatingAction/verification_sophi.m')           
        ],
        name='DDCOneTerminate'
        )
